version: '3'
services:
  airport:
    image: mikebrady/shairport-sync:latest
    container_name: shairport-sync
    restart: unless-stopped
    network_mode: host
    devices: 
      - /dev/snd
    environment:
      - AIRPLAY_NAME=Serveur
      - PGID=1000
      - PUID=1000